name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Update paper list
      run: |
        cd paper_infos
        python generate_tables.py
        ls .. -al
        git config --global user.email "1435679023@qq.com"
        git config --global user.name "marsggbo"
    - name: git push
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: docs # The folder the action should deploy.
